version: '3.8'

services:
  web:
    container_name: dataliteracy
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - '80:8000'
    env_file:
      - .env

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    restart: unless-stopped
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
